language: objective-c
os: osx
osx_image: xcode11.5
cache:
  directories:
  - Carthage
before_install:
- carthage update --platform iOS
- bundle install --path vendor/bundle
script:
- fastlane tests
env:
  global:
    secure: RGdBSzVqUoo/+YB66F8hufY4ilx6wWcSqtduXN5+aqLiuEv9IcR2E8+Kgp0bSV0MpPktAQZ4oiGRwYT7O4bzvKZgyzNYKMZgPdjyNAKMxOW88O6XDz1IcpQM/QOxAIHeTJzUbZzW1JDFGeffyULg20euZNNd98sM2uwQUyTWrqjjIHP2C+8i5ROTu1qDwCCjUBHXogZVHFnK5NVGLWJi0z1fmsy17R06lDAI3uRKL4UeCqzvYdz5KVZpgbFtdJYtr229FRq+e0/ePK0PkkCOT288JDVzYT6Ts3mFTAzTrm+0gElPFooTB6zj9tDWKKVJqwb0JOJZD2RxuhSJvNRFWLGUrk0aERzXo3khTiKrXK6dwjnBr2yVCLYlfbcWxCIO85aPI0BnpkVI+6xHVcoj+rntFgZ3Pm3gKD0EzgVTIwd3qx6YDJrtYA65qvGHvou9nZhsTIqXhnBEGh1I3CzFCsRX8p16Xmt/arNppxcpZjLZ0IsheKfNnAuJc8Lz6PbrFeeK/Luaqd+Oto6hNjqMcqmTahT7lrI38XtC8c49HwxJCex9MW3fJczQX/BSinhvB5jl5wWJVItHwpO61ICczTAWIkJKNMYHWxc2n5dcZmISUg+auH9z284uLrG2FThCSrxGY7xRFQM56a55NESff35hqVcbfDfAReKm+bgI8Eo=
notifications:
  slack:
    secure: YFNN194Ei9/WWI2ilToikVrUOKlgS6IQs4YW4V7pQelpvV0wmzRPIULj34Ygg9grO0huGZAmB5WrDiSe7xEHcqKd4f5ifCV39xu+OTcn9etbmVb2yDmIkWsPeJvcETuoznLBA0Sr7ADtpeZtad8zVNIiNsH9cux77EOu/NqMFLJ44HG6lB36Q9kWx6pA5FpZDyVvJ47Hl8Ei70Qdhzmm5u8KDsTf+Wr6dukIArC2AuM2LVz1Fl57O/wWmSiudsHmE4JqOd6FVy/o4zAfjYKFz+gI1NiwGP2bCvOR0LoSQbE66lfTAuJ9ECGtlJ33B7Xvq/YoLCe4pxmBOKfxrg2DRVvJgQFaTuz7L3LFpqnMMOvSsjOHjTSPkM8xpFRDz+/K2yB9o35RRqjFqwJFcG3t9reN8oRosJLZW4BLkI4hR4UsYEVNiDSczqSNcjfGHd5yrBSR+cpsXI3M3KRFejHYYNhDu2/sWbCMLRN8cmCyRFJ+1q6ZswXFfuzrmMdMP4lQ9zurdXSZhfANkKIEvf+SuNP97UXzZduqd8QxmvN60ZAtlxvsDbRNVRfT6NQXhupkDGTOgSJxqvFBkhSyaL52c+9+sEOU9Vz7rN87LdF0/LB0+5a3EnezhMwjXp4/x1XnX8WHdcrOZF5Lqty23XQpAL3Fb7y53vk/sq5HYci9bpg=
